//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sınav_Notları
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ismailak_EntityEntities : DbContext
    {
        public ismailak_EntityEntities()
            : base("name=ismailak_EntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_dersler> Tbl_dersler { get; set; }
        public virtual DbSet<Tbl_kulüpler> Tbl_kulüpler { get; set; }
        public virtual DbSet<Tbl_notlar> Tbl_notlar { get; set; }
        public virtual DbSet<Tbl_ogrenci> Tbl_ogrenci { get; set; }
    
        public virtual ObjectResult<kulupler_Result> kulupler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kulupler_Result>("kulupler");
        }
    
        public virtual ObjectResult<notlistesi_Result> notlistesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notlistesi_Result>("notlistesi");
        }
    }
}
