//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sınav_Notları
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ogrenci()
        {
            this.Tbl_notlar = new HashSet<Tbl_notlar>();
        }
    
        public short id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string fotograf { get; set; }
        public Nullable<short> ogrkulup { get; set; }
        public string sehir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_notlar> Tbl_notlar { get; set; }
    }
}
