//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sınav_Notları
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_kulüpler
    {
        public short kulupid { get; set; }
        public string kulupad { get; set; }
    }
}
