//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sınav_Notları
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_notlar
    {
        public short notid { get; set; }
        public Nullable<short> ogr { get; set; }
        public Nullable<short> ders { get; set; }
        public Nullable<short> sınav1 { get; set; }
        public Nullable<short> sınav2 { get; set; }
        public Nullable<short> sınav3 { get; set; }
        public Nullable<decimal> ortalama { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual Tbl_dersler Tbl_dersler { get; set; }
        public virtual Tbl_ogrenci Tbl_ogrenci { get; set; }
    }
}
